#!/bin/bash
# sorry, if we call this kind of garbage from crabat, we just get a pile of memory leaks associated with /bin/bash and not, say, Analyzer.h
valgrind -v --suppressions=/etc/root/valgrind-root.supp --tool=memcheck --leak-check=full --show-reachable=yes ./run -R 1038 -r -d -s -x -p -t 2>&1 | tee log/valgrind.log
